### ISSUE TITLE
@verdaccio/eslint-config@2.0.0 miss devDependencies

### ISSUE THREAD

**Issue by juanpicado** [verdaccio/monorepo#40]
**Describe the bug**
Using it make fails the build.

I tried to update `verdaccio-audit` and prettier is not being found.

**Expected behavior**
Dependencies should be included in any project as devDependencies.

**Screenshots**

```
➜ yarn test              
yarn run v1.17.3
$ npm run lint && jest
npm WARN lifecycle The node binary used for scripts is /var/folders/z9/wb47bj7j51n8p9h07y_11wch0000gn/T/yarn--1564387204819-0.5912425069863878/node but npm is using /Users/jpicado/.nvm/versions/node/v10.15.0/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> verdaccio-audit@1.2.0 lint /Users/jpicado/projects/@verdaccio/verdaccio-audit
> eslint . --ext .js,.ts

Error: Cannot find module 'prettier'
Occurred while linting /Users/jpicado/projects/@verdaccio/verdaccio-audit/jest.config.js:3
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:581:15)
    at Function.Module._load (internal/modules/cjs/loader.js:507:25)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Program (/Users/jpicado/projects/@verdaccio/verdaccio-audit/node_modules/eslint-plugin-prettier/eslint-plugin-prettier.js:162:26)
    at listeners.(anonymous function).forEach.listener (/Users/jpicado/projects/@verdaccio/verdaccio-audit/node_modules/eslint/lib/util/safe-emitter.js:45:58)
    at Array.forEach (<anonymous>)
    at Object.emit (/Users/jpicado/projects/@verdaccio/verdaccio-audit/node_modules/eslint/lib/util/safe-emitter.js:45:38)
    at NodeEventGenerator.applySelector (/Users/jpicado/projects/@verdaccio/verdaccio-audit/node_modules/eslint/lib/util/node-event-generator.js:251:26)
    at NodeEventGenerator.applySelectors (/Users/jpicado/projects/@verdaccio/verdaccio-audit/node_modules/eslint/lib/util/node-event-generator.js:280:22)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! verdaccio-audit@1.2.0 lint: `eslint . --ext .js,.ts`
npm ERR! Exit status 2

```

**Comment by sergiohgz** [comment]
Sorry, I forgot to add the breaking change of ESLint and Prettier in @verdaccio/eslint-config@2.0.0. Both packages were removed from dependencies to allow users use the version they like (moved to peerDependencies).

Closed #40 via 905b578
